name: flutter_codes
description: A project having flutter codes of commonly used modules.
version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  get: ^3.25.0 
  animated_splash_screen: ^1.0.1+2 
  page_transition: ^1.1.7+6 
  font_awesome_flutter: ^8.11.0 
  firebase_core: ^1.3.0 
  firebase_auth: ^1.4.1 
  google_sign_in: ^5.0.4
  shared_preferences: ^2.0.6
  cloud_firestore: ^2.2.2 
  firebase_storage: ^8.1.3 
  image_picker: ^0.8.1+1 
  firebase_analytics: ^7.0.1
  get_it: ^5.0.6
  # firebase_messaging: 
  # # onesignal_flutter: ^2.6.2
  # overlay_support: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
    # sdk: flutter
  change_app_package_name: ^0.1.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
