name: flutter_codes
description: A project having flutter codes of commonly used modules.
version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  get: ^3.24.0 # statemanagement #import 'package:get/get.dart';
  animated_splash_screen: ^1.0.1+2 #import 'package:animated_splash_screen/animated_splash_screen.dart';
  page_transition: ^1.1.7+6 #import 'package:page_transition/page_transition.dart';
  font_awesome_flutter: ^8.11.0 #import 'package:font_awesome_flutter/font_awesome_flutter.dart';
  firebase_core: ^0.7.0 #use this to initiazie our application #import 'package:fireabe_core/firebase_core.dart';
  firebase_auth: ^0.20.0+1 # for user authentication #import 'package:firebase_auth/firebase_auth.dart';
  google_sign_in: ^4.5.9 # google signin #import 'package:google_sign_in/google_sign_in.dart';
  shared_preferences: ^0.5.12+4 #import 'package:shared_preferences/shared_preferences.dart';
  cloud_firestore: ^0.16.0 #import 'package:cloud_firestore/cloud_firestore.dart';
  firebase_storage: ^7.0.0 #import 'package:firebase_storage/firebase_storage.dart';
  permission_handler: ^5.0.1+1 #only works with android &  ios #import 'package:permission_handler/permission_handler.dart';
  image_picker: ^0.6.7+21 # only supports android and ios #import 'package:image_picker/image_picker.dart';
  # path: ^1.7.0 #import 'package:path/path.dart';
  # firebase: ^8.0.0
  # flutter_web_image_picker: ^0.0.2
  file_picker: ^2.1.5+1
  # path_provider: ^1.6.27
  dio: ^3.0.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  change_app_package_name: ^0.1.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
